### ISSUE TITLE
concurrent connections need to be in a single test

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend-ICD-test#1]
https://github.com/CARTAvis/carta-backend-ICD-test/blob/db12d5fc3728ae2d9606c7faf8e4672f72713572/src/test/ACCESS_CARTA_DEFAULT_CONCURRENT.test.ts#L67

The concurrency tests need to be reconfigured to have a single test (with multiple assertions) per feature test, rather than a test for each concurrent connection. The order in which Jest executes tests is not clearly defined, but it _should_ wait for a test to finish executing (via the `done` callback) before moving on to the next test. With the current approach, this means that only a single connection is active at once.

A more appropriate approach for a test that ensures each connection returns a unique session ID would be to do the following:
- connect each socket in the `beforeAll` section (already done :+1: but remove the section sending the register viewer message to the backend, as you haven't defined an `onmessage` behaviour at this point)
- disconnect each socket in the `afterAll` section (already done :+1: )
- a single test which (a) sets up the `onmessage` callback for each connection and sends `registerViewer`. Once all callbacks are completed, assert the uniqueness of the ID of each one

While it's not essential in this case, this would be an important change of approach in general, especially when we move to performance testing, where we need to ensure that a single test sends requests for each concurrent connection in a predictable manner. 

Going forward, to avoid boilerplate code, it might make sense to implement something similar to the `backendService` of the frontend for repeated tasks, and to turn callbacks into promises or observable streams that can be merged (`Promise.all()` might be very useful in this case)

**Comment by veggiesaurus** [comment]
two other issues with the current implementation:
- the `onmessage` callback for connection _N_ is not defined until the test for connection _N_ executes. By this stage, it's probable that the `REGISTER_VIEWER_ACK` message would already have been sent, so the callback may never be called
- the event length is asserted, but if the event length is > 40 and the event name is _not_ "REGISTER_VIEWER_ACK", the `done` callback is never called, and the test will only fail by timing out
- tests should be independent. In this case, the tests below the first in the loop _require_ the result of the second test to be completed. Therefore they will always fail unless the first test in the loop is executed.. Either combine the assertions into a single test, or make the tests independent.

**Comment by zarda** [comment]
Thank you for comments. I have refactored the codes via Promise.all() . 
Another testing about "Jest.test.concurrent", this testing function is still not completed with many bugs, such as the "beforeAll" does not always work correctly before "test.concurrent()".
