### ISSUE TITLE
Upgrade after CARTA release 1.3

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend-ICD-test#100]
Improve the ICD tests

- [x] ACCESS_CARTA_DEFAULT
- [x] ACCESS_CARTA_KNOWN_SESSION
- [x] ACCESS_CARTA_NO_CLIENT_FEATURE
- [x] ACCESS_CARTA_SAME_ID_TWICE
- [x] GET_FILELIST_DEFAULT_PATH
- [x] GET_FILELIST_UNKNOWN_PATH
- [x] FILETYPE_PARSER
- [x] FILEINFO_FITS
- [x] FILEINFO_CASA
- [x] FILEINFO_HDF5
- [x] FILEINFO_MIRIAD
- [x] FILEINFO_FITS_MULTIHDU
- [x] FILEINFO_EXCEPTIONS
- [x] CURSOR_SPATIAL_PROFILE (assigned to mylin)
- [x] CURSOR_SPATIAL_PROFILE_NaN (assigned to mylin)
- [x] CHECK_RASTER_TILE_DATA (assigned to mylin)
- [x] TILE_DATA_REQUEST (assigned to mylin)
- [x] TILE_DATA_ORDER_TEST (assigned to mylin)

Reference:
[Session](https://docs.google.com/document/d/157ptxFGdX_8beUDOszlkwtnCtx79JiiE4YLO9S0Jtb0/edit#heading=h.69w7n28ys6ec)
[File browser](https://docs.google.com/document/d/1by2s1QOt70YsBERG6WhXjRt-7L-cjMk-LEGTlHriMpM/edit#heading=h.gfi6dze43uep)
[Spatial profiler](https://docs.google.com/document/d/1PvasasaT6rPtqOid4s3CJhPkoXPO05VBt9uTNt5m0UI/edit#heading=h.gfi6dze43uep)
[Raster tiles](https://docs.google.com/document/d/1rsq8IlyIQwU60hqXZobi7UntnrYQEOrtsJzmRoXnKBY/edit#heading=h.gfi6dze43uep)

**Comment by zarda** [comment]
All testing items on the list are merged.

**Comment by zarda** [comment]
keep #100?
Because the backend crash problem is still there (although the frontend will not sent the wrong tile in principle), said by @acdo2002.

**Comment by acdo2002** [comment]
Yes, refer to the backend enhancement issue ([link](https://github.com/CARTAvis/carta-backend/issues/542)) reported by @kswang1029 .
