### ISSUE TITLE
Contour

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend-ICD-test#104]
Test for contour:

- [x] CONTOUR_IMAGE_DATA
- [x] CONTOUR_IMAGE_DATA_NAN
- [x] CONTOUR_DATA_STREAM

[Contour data](https://docs.google.com/document/d/1RvTIH2664S7jBYEvaTm_D5Pd07S5cTmcL7VJlCU0Uxw/edit#heading=h.3f8qkqrtozdq)

**Comment by zarda** [comment]
Almost done but need a support of wasm for extract contour data. Will look into how to reach the requirement.

**Comment by kswang1029** [comment]
Would this help? https://github.com/facebook/zstd

**Comment by zarda** [comment]
The facebook/zstd helps to review the concepts. Will apply https://github.com/yoshihitoh/zstd-codec and implement the functionality of quantization.
