### ISSUE TITLE
Testing for moments generator

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend-ICD-test#127]
To test this functionality, we need a design [document](https://docs.google.com/document/d/19hyLFcgC9XaMiGa9g8Lw_scQRXZLDFNDTetm7GPSCaI/edit#) about the sequence and testing parameters. The simulating process can be the steps in clip:
![moments_demo](https://user-images.githubusercontent.com/10767557/91700930-24f11080-eba9-11ea-87cb-d9be9aa483cb.gif)

Design:

- [x] MOMENTS_GENERATOR_REGION_FITS
- [x] MOMENTS_GENERATOR_REGION_CASA
- [x] MOMENTS_GENERATOR_REGION_HDF5
- [x] MOMENTS_GENERATOR_CANCEL
- [x] MOMENTS_GENERATOR_SAVE
- [x] MOMENTS_GENERATOR_RUNNING_SPECTRAL
- [x] MOMENTS_GENERATOR_EXCEPT

Implement:

- [x] MOMENTS_GENERATOR_REGION_FITS
- [x] MOMENTS_GENERATOR_REGION_CASA
- [x] MOMENTS_GENERATOR_REGION_HDF5
- [x] MOMENTS_GENERATOR_CANCEL
- [x] MOMENTS_GENERATOR_SAVE
- [x] MOMENTS_GENERATOR_RUNNING_SPECTRAL
- [x] MOMENTS_GENERATOR_EXCEPT

Reference:
[document](https://docs.google.com/document/d/1RciBmqsa_bZw1vgC4J0-YSOxnlIMDQyP-MINL81MYOs/edit#heading=h.pd8c2kw8bdfy) and [issue](https://github.com/CARTAvis/carta-backend/issues/154)

**Comment by zarda** [comment]
@kswang1029 A behaviour testing for the basic sequence of moments generator is added on design document. There is a framework, which follows the operations in demo clip. Suppose this framework could be a basic boilerplate in this series of test.

**Comment by kswang1029** [comment]
@zarda the test design needs a major revision. Please refer to the comments in https://docs.google.com/document/d/19hyLFcgC9XaMiGa9g8Lw_scQRXZLDFNDTetm7GPSCaI/edit#

Please let me know when you finished all the change requests. Thanks.

**Comment by zarda** [comment]
@kswang1029 Could you take a look at current design document if there is any insufficient part? Thanks.

**Comment by kswang1029** [comment]
comments made. please refer to the doc.

**Comment by kswang1029** [comment]
More comments are made. Please check.
