### ISSUE TITLE
add tests for spectral line query

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#133]
- [x] design doc
- [x] implementation

**Comment by acdo2002** [comment]
The preliminary designed doc is [here](https://docs.google.com/document/d/1mWDuv_dWNpTxPlxP3uXTWvDoo2Oz-fop_puXCwewVwc/edit#) 

Case 1: open an image, and query the spectral line interval exclude the z-axis freq. (simulate people query any line in the archive)
Case 2: open an image, request spectral line profiler and query the spectral line for plotting.

Any suggestion is welcome!
