### ISSUE TITLE
add tests for shared region analytics

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#134]
ICD testing for the condition with matching images.

[Design](https://docs.google.com/document/d/197Y1rrj7i7J1PP6NvNJuf6UK-_ZTZjc8ybD_xG6GHXw/edit?usp=sharing):

- [x] MATCH_SPATIAL
- [x] MATCH_SPECTRAL
- [x] MATCH_STATS
- [x] MATCH_STATS_WIDE
- [x] MATCH_STATS_BORDERLINE
- [x] MATCH_STATS_WIDE_BORDERLINE

Implementation:

- [x] MATCH_SPATIAL
- [x] MATCH_SPECTRAL
- [x] MATCH_STATS
- [x] MATCH_STATS_WIDE
- [x] MATCH_STATS_BORDERLINE
- [x] MATCH_STATS_WIDE_BORDERLINE

**Comment by zarda** [comment]
@kswang1029 Would you mind having several hints about how to act these testing on frontend? May the backend need to prepare or send any data to help these actions, such as stats or profile?

**Comment by kswang1029** [comment]
I can make the test design for this one. Please focus on other tests first.

**Comment by zarda** [comment]
Could you give any hint about this implementation? E.g. which ICD command or UI operation.
I assume to create a lot of regions and try to request their statistics.

**Comment by zarda** [comment]
@kswang A few questions about the implementation:
Duo to the request of matching image either in xy or z from frontend, the carta-backend will follow whatever the channel in the given message and return a right channel. This means the backend have no idea of matching.

These matching numbers are calculated on frontend, e.g. [0, 1, 2, 3, 4] : [120, 119, 118, 117], while we turning on the matching switch of 'xy' or 'z'. After the matching, only animator will need to send this series of matching number.

If this testing need to test this feature on frontend, we may learn the code on frontend. Matching channel needs to apply the feature: WCS Matching. Which may involve to AST lib.
Do I have to porting this feature from frontend to ICD testing?
Or we could just send the same parameters whatever sent from frontend. That is to imitate the ICD commands only.
Is that right?

**Comment by kswang1029** [comment]
There is no need to implement the logic of matching in the test. The whole idea here is to test the business logic of the backend on request handling.

**Comment by kswang1029** [comment]
Another key feature here is on the matched images, regions are approximated as polygons to take projection into account. Thus it is critical to check analytics in this case.

**Comment by zarda** [comment]
@kswang1029 Would you mind having a review? Thanks.

**Comment by zarda** [comment]
The testing MATCH_STATS relates to the [issue](https://github.com/CARTAvis/carta-backend/issues/607).
