### ISSUE TITLE
add tests for animation playback of raster plus a set of contours from different matched images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#135]
Testing of animator: playback the image with contour lines.

design [doc](https://docs.google.com/document/d/1fUgxr6aNtvJrYcl_eISI6MwQwOqXvDIfczaHjAsTCj0/edit?usp=sharing):

- [x] ANIMATOR_CONTOUR
- [x] ANIMATOR_CONTOUR_MATCH

implementation :

- [x] ANIMATOR_CONTOUR
- [x] ANIMATOR_CONTOUR_MATCH

**Comment by zarda** [comment]
@kswang1029 Would you mind taking a look at this testing? Thanks.

**Comment by kswang1029** [comment]
The current design include animating raster + its contour. We need other tests with one raster + at least two contour sets from different matched images.

**Comment by zarda** [comment]
Could you have more detailed operating steps about this test? 
As we open an image file on frontend and applied its contour, we could get the contour lines for current raster image. If we change to another image, which could be appended, there will be no contour lines. In the meanwhile, we start animating, there is no contour line for the new appended image.
Or did you mean to test that we open many images with contour and start to animate one of them?

**Comment by kswang1029** [comment]
Try the following steps with GUI and observe the ICD message flow
1. load HD163296_CO_2_1.fits and append HD163296_13CO_2_1.fits
2. generate contours for each image
3. with the image list widget, click "XY" and "Z" of HD163296_13CO_2_1.fits (become green)
4. start animation playback. there should be two sets of contours animating

**Comment by zarda** [comment]
@kswang1029  Please review the design doc. Thanks.
