### ISSUE TITLE
add catalog tests

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#136]
- [x] design doc
- [x] implementation

**Comment by acdo2002** [comment]
[Here](https://docs.google.com/document/d/1EDDJ2bV4Mzqo1N6C_D8aK9NofXv_B8roRy4J9JeXyIs/edit?usp=sharing) is the design doc, @kswang1029 please check it. So far I didn't find any large-size catalog file, if there is any existed catalog file, please let me know, I can implement an additional test with large-size catalog file.

**Comment by kswang1029** [comment]
@acdo2002 please check the images and the catalog files in set_cosmos

**Comment by kswang1029** [comment]
@acdo2002 I added few suggestions in the doc. please check.
