### ISSUE TITLE
Check the consistency of tile sequence 

### ISSUE THREAD

**Issue by acdo2002** [CARTAvis/carta-backend-ICD-test#145]
check the tile sequence between different OS servers.
Since [PR#143](https://github.com/CARTAvis/carta-backend-ICD-test/pull/143) Anthony found:

> Problem getting tile layer=2, x=3, y=3
> Problem getting tile layer=2, x=3, y=0
> Problem getting tile layer=2, x=0, y=3
> Problem getting tile layer=2, x=0, y=0

when running `CLOSE_FILE_TILE.test.ts` with MacOS (although this problem does not affect the CLOSE_FILE related ICD test itself!). However the message does not show up on LinuxOS.

**Comment by zarda** [comment]
The frontend could adapt the tile scheme to the present screen. We might need additional function to generate these ids handy in order to the more custom testing senses, e.g. tileCoordinates = (x, y, layer) => (layer << 24) | (y << 12) | x;

**Comment by zarda** [comment]
We could imagine the use cases from the existent testing, such as any extended testing about the feature: tile date.
Do we need to test the feature of room in/out? Some extreme situation may room in/out while animating or focusing on certain region. This testing case needs to add a new issue.

**Comment by acdo2002** [comment]
I check the tiles number
tile layer=2, x=3, y=3 corresponds to "33566723"
tile layer=2, x=3, y=0 corresponds to "33554435"
tile layer=2, x=0, y=3 corresponds to "33566720"
tile layer=2, x=0, y=0 corresponds to "33554432"

then I suppose the x & y (i.e. i & j in Hengtai's code) allow the `layer+1`. If layer=2, x & y could be [0,1,2,3], there are 4^4=16 tiles in total.

I change the tile = [33566723,33554435,33566720,33554432] in the `CLOSE_FILE_TILE.test.ts` and run it on the almc (MacOS) with ws. The backend log (verbose=true & perflog=true) does not show the same warning...I cannot create the same test result...

@ajm-asiaa Could you check it again, whether it still shows up the warning log...? ><" (I have built the backend dev branch on almac/mingyi yesterday, the branch commit: `ee68acf`)

I also checked the UI with the image, the frontend shows these tile number `[33566723,33554435,33566720,33554432]` in the console.log too .

**Comment by kswang1029** [comment]
is this issue about the sequence of the received tiles?

**Comment by acdo2002** [comment]
@kswang1029
I change the sequence and run it with MacOS backend, the log looks the same (now almac backend run the same behavior to the centOS backend: no warning message created), I cannot create the warning. 
They both look fine with these tiles.

**Comment by ajm-asiaa** [comment]
@acdo2002 You're right. I don't see those warnings anymore for some reason. Thanks for checking.
