### ISSUE TITLE
RESUME_SESSION.test.ts induce the backend crash

### ISSUE THREAD

**Issue by acdo2002** [CARTAvis/carta-backend-ICD-test#148]
Condition: 
I test the ws and wss with RESUME_SESSION.test.ts, and found the test can induced the backend crash.
backend log on acdc:

> -bash-4.2$ ./carta_backend base=/scratch/images root=/scratch/images port=4013 verbose=true perflog=true threads=4 omp_threads=8
> ./carta_backend: Version 1.4
> Listening on port 4013 with root folder /scratch/images, base folder /scratch/images, 4 threads in worker thread pool and 8 OMP threads
> Session 1 (Wed Nov  4 07:20:28 2020): Client 1 [::ffff:127.0.0.1] Connected. Num sessions: 1
> Load 640x800 image to cache in 44.063 ms at 11.6197 MPix/s
> Fill image histogram in 1.595 ms at 135.579 MPix/s
> [libprotobuf FATAL /usr/local/include/google/protobuf/repeated_field.h:1514] CHECK failed: (index) < (current_size_): 
> Error: CHECK failed: (index) < (current_size_): 

Client: `npm test RESUME_SESSION.test.ts`

The behavior does not appear on the UI frontend. The frontend still can re-connect to the server after Resume...

**Comment by zarda** [comment]
This issue is solved by #141
