### ISSUE TITLE
Session disconnect if spectral line query request a wider frequency range

### ISSUE THREAD

**Issue by acdo2002** [CARTAvis/carta-backend-ICD-test#149]
related to PR #146 
In principle, the session should still connect until I close the session.
However I found the session will automatically close if I request a wider frequency range (e.g. min: 230500, max: 231000) on spectral line query function. 
i.e.

> Session 18 (Wed Nov  4 08:05:05 2020): Client 18 [::ffff:127.0.0.1] Connected. Num sessions: 3
> Load 1920x1920 image to cache in 40.229 ms at 91.6354 MPix/s
> Fill image histogram in 15.164 ms at 202.196 MPix/s
> Fill spatial profile in 0.001 ms
> Fill spatial profile in 0.19 ms
> Mean filter 1920x1920 raster data to 240x240 in 28.66 ms at 2.00977 MPix/s
> Compress 240x240 tile data in 1.23 ms at 46.8293 MPix/s
> Get tile data group in 30.948 ms
> Session 18 (Wed Nov  4 08:05:07 2020): Client 18 [::ffff:127.0.0.1] Disconnected. Remaining sessions: 3

This behavior is unexpected. If I request a narrower frequency range (e.g. min: 230500, max: 230900), the session is still connected. 
i.e. 

> Session 17 (Wed Nov  4 08:00:14 2020): Client 17 [::ffff:127.0.0.1] Connected. Num sessions: 2
> Load 1920x1920 image to cache in 34.534 ms at 106.747 MPix/s
> Fill image histogram in 16.539 ms at 185.386 MPix/s
> Fill spatial profile in 0.001 ms
> Fill spatial profile in 0.139 ms
> Mean filter 1920x1920 raster data to 240x240 in 28.658 ms at 2.00991 MPix/s
> Compress 240x240 tile data in 1.222 ms at 47.1358 MPix/s
> Get tile data group in 30.913 ms

The frontend UI does not appear such behavior. frontend UI works fine within any <20GHz interval range.

**Comment by kswang1029** [comment]
The log suggests it is loading an image and getting relevant data. When did you request a spectral line query? Before or after loading an image?

**Comment by acdo2002** [comment]
after loading an image.

Hengtai is investigating this issue now, he suggests the problem comes from the websockt.
Once he changed to previous websocket (jsdom), it passes, the problem looks like that is related to the limitation of returned data size.
Hengtai and I are still discussing it.

**Comment by zarda** [comment]
Suppose this issue relates to the websocket lib. We may try it by solutions: 1) enlarge the parameter of chuck size in lib if possible; 2) change the websocket lib.

**Comment by zarda** [comment]
A quick solution works at the moment: enlarge the `maxReceivedFrameSize` in `/websocket/lib/WebSocketClient.js` of NPM lib upto about `0x01000000`.

**Comment by zarda** [comment]
I got the solution. Will commit it soon.

**Comment by acdo2002** [comment]
If I set:
assertItem.setSpectralLineReq.frequencyRange: { min: 230500, max: 231000 }
the automatically disconnection is still there...

**Comment by zarda** [comment]
> If I set:
> assertItem.setSpectralLineReq.frequencyRange: { min: 230500, max: 231000 }
> the automatically disconnection is still there...

Please change the testing backend from wss://***/socketdev to others, e.g. .../socket5012. The backend instance may be crashed.
