### ISSUE TITLE
Refactor test for PER_

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend-ICD-test#160]
Refactor these tests by Client.streamUntil(). This update needs to Clean code as well.

- [x] PER_CONTOUR_2D
- [x] PER_CUBE_HISTOGRAM
- [x] PER_CUBE_HISTOGRAM_CANCEL
- [x] PER_CUBE_HISTOGRAM_HDF5

**Comment by kswang1029** [comment]
Could you also rename the script name from per_xxx to perf_xxx? This will be more clear to distinguish different types of tests.

**Comment by kswang1029** [comment]
Are these performance tests? If so could you rename them from per_xxx to perf_xxx? This will be more clear to distinguish different types of tests.

**Comment by kswang1029** [comment]
Nevermind. Those seem to be all functional tests.
