### ISSUE TITLE
add test for per-plane-beam images

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#173]
cf https://github.com/CARTAvis/carta-backend/pull/664

Design [doc](https://docs.google.com/document/d/1by2s1QOt70YsBERG6WhXjRt-7L-cjMk-LEGTlHriMpM/edit#):
- [x] OPENFILE_FITS_BEAMTABLE
- [x] OPENFILE_CASA_BEAMTABLE

Implement:
- [x] OPENFILE_FITS_BEAMTABLE
- [x] OPENFILE_CASA_BEAMTABLE

**Comment by zarda** [comment]
Add a new test on the design doc: [FILEINFO_FITS_BEAMTABLE](https://docs.google.com/document/d/1by2s1QOt70YsBERG6WhXjRt-7L-cjMk-LEGTlHriMpM/edit#). Please review.

**Comment by kswang1029** [comment]
7a is for which channel? Otherwise it reads fine. Please also add a test for FITS format too. HDF5 at the moment doesn’t support per-plane-beam. MIRIAD format can be skipped in this test.

**Comment by zarda** [comment]
This is a table so there must be a header for following column. 7) a) checks the headers of this beam table.
Will add that for FITS image.
