### ISSUE TITLE
add test for region files in dos format

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#174]
cf https://github.com/CARTAvis/carta-backend/pull/658

**Comment by zarda** [comment]
Add a new test entry in the end of [design document](https://docs.google.com/document/d/1ovy1Dx7kraWW63x-bws7H5jpwTU2OxgzPJIM427Jp30/edit#heading=h.80yldwdfqqmk), naming "DS9_REGION_IMPORT_DOS", please review.

**Comment by kswang1029** [comment]
The design is fine please proceed
