### ISSUE TITLE
add tests for loading multiple files including images, region files, and catalog files

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#176]
cf https://github.com/CARTAvis/carta-frontend/pull/1289

[design](https://docs.google.com/document/d/1by2s1QOt70YsBERG6WhXjRt-7L-cjMk-LEGTlHriMpM/edit#heading=h.snxxhbjaquoh):

implement:

- [x] IMPORT_MULTIPLE_REGION
- [x] IMPORT_MULTIPLE_CATALOG
- [x] IMPORT_MULTIPLE_IMAGE

**Comment by zarda** [comment]
The behavior on the frontend is open file one by one with other requests. The testing could be implemented by triggering the open_file consecutively without any other requests, such as cursor, x/y profile, or tiled raster image.

**Comment by zarda** [comment]
Do we need a more test for this issue other than the test OPEN_IMAGE_APPEND in the design [document](https://docs.google.com/document/d/1by2s1QOt70YsBERG6WhXjRt-7L-cjMk-LEGTlHriMpM/edit#heading=h.t2imz8k739j5)?

**Comment by zarda** [comment]
This issue could be re-open when the frontend changed the way of request to ask multiple images in one request.

**Comment by kswang1029** [comment]
Which test is addressing this?

**Comment by zarda** [comment]
Updated 3 new testing for region, catalog, and image files in a consecutive opening by frontend.
