### ISSUE TITLE
Session test updating for ICD 19

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-backend-ICD-test#178]
The ICD Session tests (`src/test/ACCESS_CARTA_DEFAULT.test.ts`, `src/test/ACCESS_CARTA_KNOWN_SESSION.test.ts`, `src/test/ACCESS_CARTA_NO_CLIENT_FEATURE.test.ts`, `src/test/ACCESS_CARTA_SAME_ID_TWICE.test.ts`, and `src/test/ACCESS_CARTA_DEFAULT_CONCURRENT.test.ts`) require updating due to the ICD change. 
It appears to need more than changing the number from 18 to 19. e.g.

```
● ACCESS_CARTA_DEFAULT tests: Testing connections to the backend › send "REGISTER_VIEWER" to "ws://localhost:3002" with session_id=0 & api_key="" › REGISTER_VIEWER_ACK.success = True
    expect(received).toBe(expected) // Object.is equality
    Expected: true
    Received: false
      38 | 
      39 |         test("REGISTER_VIEWER_ACK.success = True", () => {
    > 40 |             expect(RegisterViewerAckTemp.success).toBe(true);
         |                                                   ^
      41 |         });
      42 | 
      43 |         test("REGISTER_VIEWER_ACK.session_id is not None", () => {
      at Object.test (src/test/ACCESS_CARTA_DEFAULT.test.ts:40:51)
  console.warn src/test/CLIENT.ts:164
    Server event has ICD version 19, which differs from frontend version 18. Errors may occur
```

**Comment by zarda** [comment]
There is another issue about file info update of ICD, we will give all related message a default HDU number, i.e. HDU: "0".
The @acdo2002 is working on this part.
