### ISSUE TITLE
add test for loading FITS with incomplete headers

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#185]
related issue: https://github.com/CARTAvis/carta-backend/issues/596 and PR: https://github.com/CARTAvis/carta-backend/pull/684

**Comment by zarda** [comment]
@kswang1029 Would you mind adding a testing image with incomplete header? 
Is the /set_QA/broken_header.mirad a right target?

**Comment by kswang1029** [comment]
yes set_QA/broken_header.mirad is one. Please also use the attached images for the test (try to load with dev-backend via GUI to see if they load or not then define the test cases. Thanks.

https://drive.google.com/file/d/1KVCvLAlNfSW12W51w9ot-ggthPC48IbE/view?usp=sharing

**Comment by zarda** [comment]
Got it and ran the files on late /dev. All images are opened but the `Jordan_case.fits` fails and gave an error message:
```
TabularCoordinate - start and end values in table must differ Select another file from the folder.
```

**Comment by kswang1029** [comment]
it is a known issue but the test can still check the error message and make sure the backend won't crash.

**Comment by zarda** [comment]
Please review the testing design FILEINFO_FITS_BROKEN on [Doc](https://docs.google.com/document/d/1by2s1QOt70YsBERG6WhXjRt-7L-cjMk-LEGTlHriMpM/edit#heading=h.r69xgubd8hdp).
