### ISSUE TITLE
Improve ICD test reliability: session

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-backend-ICD-test#186]
In `src/test/ACCESS_WEBSOCKET.test.ts` this test sometimes fails for an unknown reason:

> ✕ should connect to "wss://echo.websocket.org". (3112ms)

Maybe we should simply remove it.

**Comment by kswang1029** [comment]
If we ready need to test this the echoing server should be the same as the server where backend is running. Checking an external server does not help and introduce extra uncertainties.

**Comment by ajm-asiaa** [comment]
That is already getting done in the next sub-test:

    ✓ should connect to "ws://localhost:3002". (9ms)

**Comment by kswang1029** [comment]
I mean set up an wss echoing service locally in the same backing running test server.

**Comment by ajm-asiaa** [comment]
I know we used to do the ICD tests via wss:// across different systems, but later switched back to ws:// as it was easier to manage.

If we really want to test wss perhaps we could try connecting to the 'dev' branch running on our carta demo server as that already uses wss. However, that would not make the tests portable if anyone else wanted to deploy the tests at their own institution.

**Comment by kswang1029** [comment]
Alternatively if we keep using an external service for wss checking, it would be good to try few times if the current trial failed.
