### ISSUE TITLE
Improve ICD test reliability: spectral line query

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-backend-ICD-test#187]
in `src/test/SPECTRAL_LINE_QUERY_INTENSITY_LIMIT.test.ts` a few tests sometimes fail on MacOS and Ubuntu

It looks like it may be something related to this:

```
    Expected: "CH3CHNH2COOH-I"
    Received: "gGG'g-CH2OHCH2CH2OH"

    Expected: undefined
    Received: "CH3CHNH2COOH-I"
```

**Comment by kswang1029** [comment]
Is it failing sometimes or always? If it is always now but passing before it might be due to splatalogue database update

**Comment by ajm-asiaa** [comment]
Sometimes. 
The tests apparently passed on `dev` branch commit `9cde82d`, but then failed shortly after on the same day with `dev` branch commit `e917248` (and in that case they passed on CentOS7 but failed on Ubuntu and MacOS).

**Comment by acdo2002** [comment]
I think it might be due to database update, because I cannot reproduce the failure now on almac MacOS. 
At least I repeat 10 times, they are working fine. `dev` branch commit `e917248`

According to the log, I suppose that the splatalogue database still response to our ICD request but takes longer time, then the returned messages misorder (due to the update?), I can thinking about how to improve this situation.

**Comment by kswang1029** [comment]
I would say it is due to db update _only_ if we see test _always_ failing based on your test design by checking specific entries.

**Comment by kswang1029** [comment]
One of the characteristics of the returned entries is they should be sorted in rest frequency. You can validate if this is true before checking the contents.

**Comment by ajm-asiaa** [comment]
Only this part in `SPECTRAL_LINE_QUERY_WIDE_FREQ.test.ts` doesn't seem to consistently pass,  even after increasing `"spectralLineRequestWide"` to `40000`.

```
 ✕ (Step 1) Sent & return SPECTRAL_LINE_RESPONSE within 40000ms (40007ms)
```
But sometimes it passes quickly:
```
✓ (Step 1) Sent & return SPECTRAL_LINE_RESPONSE within 40000ms (15661ms)
```
```
✓ (Step 1) Sent & return SPECTRAL_LINE_RESPONSE within 30000ms (29570ms)
```

Could it be a slow network sometimes? I'm not sure how it could be fixed.

**Comment by acdo2002** [comment]
Step 1 is sending the spectralLineRequest to CARTA, then CARTA sent request to splatalogue database.
I may prefer the slow network explanation..., it seems taking to much of time (i.e. 40000ms)
If I connect to socketdev, it takes about <15000ms.
