### ISSUE TITLE
FILETYPE_PARSER expected FILE_LIST_RESPONSE.directory is incorrect

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend-ICD-test#2]
The returned directory is the path relative to root, so that <root>/<directory> is the path to the directory for the file list.  When the directory is a subdirectory of root, the returned directory is just the directory, e.g. "set_QA" not "./set_QA".  When the directory is the root directory itself, it is "." but the backend does not include "." in any other directory path.

**Comment by zarda** [comment]
This unexpectation can be reproduced as setting "root = base".

**Comment by pford** [comment]
Tested with root=base and with default root="/".  Test is fixed.
