### ISSUE TITLE
Add test which compares opening an HDF5 file to opening the original FITS file

### ISSUE THREAD

**Issue by confluence** [CARTAvis/carta-backend-ICD-test#201]
Suggestion: a test which checks that an IDIA HDF5 file (with a large selection of header entries) does not produce any additional errors when it is opened, when compared to the original FITS file.

This would be helpful for picking up issues like the two FITS -> HDF5 -> FITS header parsing issues which were fixed in [backend PR #750](https://github.com/CARTAvis/carta-backend/pull/750).

I say no _additional_ errors, because FITS and HDF5 files are parsed slightly differently, and in some cases (e.g. a header entry with a malformed date) opening a FITS file produces a few more errors than opening the same file after conversion. So results may not always be identical, but the test should check that no _new_ errors have been introduced by the HDF5 format.

Most of these kinds of parsing issues will go away when we start storing a copy of the original header in the HDF5 file -- then we will be able to use that header instead of reconstructing it from the individual HDF5 attributes. But the test may still pick up other errors which could occur when a file is opened.

**Comment by veggiesaurus** [comment]
do you not think this should be a unit test instead? It's not really reliant on the ICD itself?

**Comment by confluence** [comment]
I think you're right; I just filed this here because this was what we were using for testing. Should we make a specific issue in the backend for listing use cases which should be covered by unit tests, or would it be too broad?

**Comment by veggiesaurus** [comment]
> I think you're right; I just filed this here because this was what we were using for testing. Should we make a specific issue in the backend for listing use cases which should be covered by unit tests, or would it be too broad?

Let's make one, and then we can turn it into an epic and peel off individual issues and story point them
