### ISSUE TITLE
Improve ICD test reliability: animator 2

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-backend-ICD-test#206]
I notice on MacOS that the `src/test/ANIMATOR_CONTOUR_MATCH.test.ts` test sometimes fails. 
It fails because the backend has crashed from the previous test.
The previous test is `src/test/ANIMATOR_PLAYBACK.test.ts` however, that appears to pass fine.

I tried running the animator tests in sequence on MacOS, and I found the backend crashes with the following error:
```
carta_backend(19219,0x110a9ce00) malloc: *** error for object 0x7000000010: pointer being freed was not allocated
carta_backend(19219,0x110a9ce00) malloc: *** set a breakpoint in malloc_error_break to debug
```

Perhaps that the reason? What could be causing it?

**Comment by acdo2002** [comment]
Ok, will do. I will check it later!

**Comment by kswang1029** [comment]
please also check if ANIMATION_FLOW_CONTROL is properly triggered from the test script. This test involves quite some messages _per channel_. We need to make sure ANIMATION_FLOW_CONTROL is only tiggered when all relevant messages have been received by the test script otherwise an improper ANIMATION_FLOW_CONTROL may lead to problems like this I am guessing.

**Comment by ajm-asiaa** [comment]
I have done a little more investigation. It seems on MacOS, after the `src/test/ANIMATOR_CONTOUR.test.ts` test passes successfully, but then the carta-backend gives a segmentation fault. 
A warning backend message is: 
```
[warning] Session 1 reference count is not 0 (5) on deletion!
```
I'm not sure if it is related?

In the ICD test, if I just comment out the last line i.e. `afterAll(() => Connection.close());` then the backend doesn't crash.
The warning message still comes up, but it says:
```
[warning] Session 1 reference count is not 0 (0) on deletion!
```

I tried to reproduce it in the GUI by opening the M17_SWex.fits image, adding contours, and starting the animation playback, but that seems to be fine.

**Comment by zarda** [comment]
Could not reproduce a similar issue on my local environment of macbook. Even if my developing branch is fine for all animator_ testing.

**Comment by ajm-asiaa** [comment]
Whew! I'm glad you were able to reproduce the issue on another Mac!

**Comment by acdo2002** [comment]
So far I cannot reproduce it with GUI. (if set the backend is almac MacOS).
and so far I also cannot reproduce the crash with `npm test src/test/ANIMATOR_CONTOUR.test.ts src/test/ANIMATOR_PLAYBACK.test.ts` with almac MacOS.

But I have produced the crash only with repeating `npm test src/test/ANIMATOR_CONTOUR.test.ts` many times. the log shows
```
[2021-03-09 17:42:01.739] [debug] WebSocket closed with code 1005 and message ''.
[2021-03-09 17:42:01.739] [info] Client 10 [172.21.6.133] Deleted. Remaining sessions: 9
[2021-03-09 17:42:01.739] [warning] Session 10 reference count is not 0 (2) on deletion!
[2021-03-09 17:42:01.820] [debug] 0x7fae26039400 ~Session 8
zsh: segmentation fault 
```

**Comment by ajm-asiaa** [comment]
I feel that it is easy to crash if all animator tests are run in sequential order. Running them in a script like this:

```
#!/bin/bash
CI=true npm test src/test/ANIMATOR_DATA_STREAM.test.ts
CI=true npm test src/test/ANIMATOR_NAVIGATION.test.ts
CI=true npm test src/test/ANIMATOR_PLAYBACK.test.ts
CI=true npm test src/test/ANIMATOR_CONTOUR_MATCH.test.ts
CI=true npm test src/test/ANIMATOR_CONTOUR.test.ts
```
I tried some sleep command between each test e.g. `sleep 10`, but that does not help.

**Comment by kswang1029** [comment]
This is with one backend process so if one test ends and results the backend in an unexpected state, the following test might be affected I guess.

**Comment by ajm-asiaa** [comment]
So the unexpected backend state is probably indicated by these warning messages:

> [warning] Session 10 reference count is not 0 (2) on deletion!

What is this "reference count"?

**Comment by kswang1029** [comment]
there is an ongoing issue https://github.com/CARTAvis/carta-backend/issues/769 with a similar warning message.
I am not sure what that means.
