### ISSUE TITLE
Improve ICD test reliability: moments 2

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-backend-ICD-test#214]
I see we had a failure of `src/test/MOMENTS_GENERATOR_FITS.test.ts` on Ubuntu.

>     Moment generator
>       ✕ Receive a series of moment progress (4302ms)
>       ✕ Receive 13 REGION_HISTOGRAM_DATA (9ms)
>       ✕ Assert MomentResponse.success = true
>       ✕ Assert MomentResponse.openFileAcks.length = 13
>       ✕ Assert all MomentResponse.openFileAcks[].success = true
>       ✕ Assert all openFileAcks[].fileId > 0 (1ms)
>       ✕ Assert openFileAcks[].fileInfo.name
>       ✕ Assert openFileAcks[].fileInfoExtended (1ms)
>       ✕ Assert openFileAcks[].fileInfoExtended.headerEntries.length = 71
>       ✕ Assert openFileAcks[].fileInfoExtended.computedEntries.length = 15 (1ms)

>   ● MOMENTS_GENERATOR_FITS: Testing moments generator for a given region on a fits image › Moment generator › Receive 13 REGION_HISTOGRAM_DATA
>     expect(received).toEqual(expected) // deep equality
>     Expected: 13
>     Received: 0

The same test passed fine on CentOS and MacOS, plus can pass on Ubuntu at other times

>  ✓ Receive a series of moment progress (344ms)

Is it possible to make the test more reliable?

**Comment by zarda** [comment]
The best option is to move this test temporary out the CI until we get the reason.
The current testing result means this functionality could not complete as we expected sometimes.
If the behaviour could not be anticipated, we might not need to test it.

**Comment by ajm-asiaa** [comment]
OK. The only problem now is that all the ICD tests are hardcoded into the Jenkinsfile. 
To remove a test, a new Jenkinsfile commit would need to be make on the carta-backend repository and merged into everyone's branches...
Would it be easy to modify `src/test/MOMENTS_GENERATOR_FITS.test.ts` itself in order to skip tests?

**Comment by kswang1029** [comment]
> I see we had a failure of `src/test/MOMENTS_GENERATOR_FITS.test.ts` on Ubuntu.
> 
> > ```
> > Moment generator
> >   ✕ Receive a series of moment progress (4302ms)
> >   ✕ Receive 13 REGION_HISTOGRAM_DATA (9ms)
> >   ✕ Assert MomentResponse.success = true
> >   ✕ Assert MomentResponse.openFileAcks.length = 13
> >   ✕ Assert all MomentResponse.openFileAcks[].success = true
> >   ✕ Assert all openFileAcks[].fileId > 0 (1ms)
> >   ✕ Assert openFileAcks[].fileInfo.name
> >   ✕ Assert openFileAcks[].fileInfoExtended (1ms)
> >   ✕ Assert openFileAcks[].fileInfoExtended.headerEntries.length = 71
> >   ✕ Assert openFileAcks[].fileInfoExtended.computedEntries.length = 15 (1ms)
> > ```
> 
> > ● MOMENTS_GENERATOR_FITS: Testing moments generator for a given region on a fits image › Moment generator › Receive 13 REGION_HISTOGRAM_DATA
> > expect(received).toEqual(expected) // deep equality
> > Expected: 13
> > Received: 0
> 
> The same test passed fine on CentOS and MacOS, plus can pass on Ubuntu at other times
> 
> > ✓ Receive a series of moment progress (344ms)
> 
> Is it possible to make the test more reliable?

any idea why this fails?

**Comment by zarda** [comment]
Due to the issue on backend about releasing resource may not be stable, we could try to assign different 'fileId' in each test. This could minimize the competition of using the same fileId, i.e. fileId=0 .
