### ISSUE TITLE
Improve ICD test reliability: region statistics

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-backend-ICD-test#220]
I'm not sure if this is a fluke or not, but there was a problem with the `src/test/REGION_STATISTICS_RECTANGLE.test.ts` test on MacOS. You can see more details [here](https://carta.asiaa.sinica.edu.tw/blue/organizations/jenkins/carta-backend/detail/dev/303/pipeline/685):

It seems it didn't like the `HDF5` file, but other errors are related to the `image` file

>    Open image "M17_SWex.hdf5" to set image view
>       ✕ Prepare (4101ms)

>  ● REGION_STATISTICS_RECTANGLE: Testing statistics with rectangle regions › Open image "M17_SWex.image" to set image view › SET STATS REQUIREMENTS on region #-1 › REGION_STATS_DATA.region_id = -1
>     expect(received).toEqual(expected) // deep equality
>     Expected: -1
>     Received: 4
> 
> 
>   ● REGION_STATISTICS_RECTANGLE: Testing statistics with rectangle regions › Open image "M17_SWex.image" to set image view › SET STATS REQUIREMENTS on region #-1 › Assert & Check REGION_STATS_DATA.statistics
>     expect(received).toBeCloseTo(expected, precision)
>     Expected: 216248
>     Received: 0
> 
>   Expected precision:    4
>   Expected difference: < 0.00005
>   Received difference:   216248

The test worked fine on CentOS and Ubuntu.

**Comment by ajm-asiaa** [comment]
Both MacOS and the two linux versions seem to be using the same HDF5 file (185333128 Bytes in size).

**Comment by ajm-asiaa** [comment]
The second time I ran it, it actually passed on MacOS, so it might be hard to reproduce the issue. I wonder if anything could be done to make the test more reliable?

**Comment by acdo2002** [comment]
I met (maybe) a similar situation this morning.
When I review the MOMENT related tests with almac macOS. I found a vary weird situation. 
I run several tests but the backend automatically crashed. And I would like to repeat this issue but the the second time all test passed and the backend is still alive...
