### ISSUE TITLE
Open pv & uv images

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend-ICD-test#221]
Ref: Support UV and pV images [#663](https://github.com/CARTAvis/carta-backend/issues/663) and [PR776](https://github.com/CARTAvis/carta-backend/pull/776)

Will test opening the images: M17_SWex_pv.fits(FITS) and M17_SWex_pv.image(CASA).

Design [document](https://docs.google.com/document/d/1by2s1QOt70YsBERG6WhXjRt-7L-cjMk-LEGTlHriMpM/edit#heading=h.gfi6dze43uep)

Implement:
OPEN_IMAGE_PV

**Comment by zarda** [comment]
@kswang1029 Please review the design document about OPEN_IMAGE_PV & OPEN_IMAGE_CASA.
Thanks.

**Comment by kswang1029** [comment]
thanks they look fine. We also need _file info_ tests for PV images and those CASA image variants.
