### ISSUE TITLE
Export sub image

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend-ICD-test#233]
From backend issue [#618](https://github.com/CARTAvis/carta-backend/issues/618), the feature is merged at the moment.

ICD commands:
[SAVE_FILE](https://carta-protobuf.readthedocs.io/en/latest/messages.html#savefile)
[SAVE_FILE_ACK](https://carta-protobuf.readthedocs.io/en/latest/messages.html#savefileack)

To [test](https://docs.google.com/document/d/1tPyqQp8Rd2yH5bhdFT676nePbfLWVfF26_l3hKVHrAo/edit#):
- [x] Export a image in format of casa or fits
- [x] Export subimage in a spectral range of original image
- [x] Export subimage in a combination of stokes to original image
- [x] Export a chopped region of original image
- [x] Export a chopped region of shared image
- [x] Drop degenerated axes
- [x] Handle error as chop a region outside the image

To implement:

- [x] EXPORT_IMAGE_ORIGINAL
- [x] EXPORT_IMAGE_CHANNEL
- [x] EXPORT_IMAGE_STOKES
- [x] EXPORT_IMAGE_CHOP
- [x] EXPORT_IMAGE_CHOP_SHARED
- [x] EXPORT_IMAGE_DROP_DEG
- [x] EXPORT_IMAGE_ERROR_MESSAGE

**Comment by acdo2002** [comment]
I will work on (1)-(3)
Heng-tai will work on (4)-(6).

**Comment by zarda** [comment]
@kswang1029 The design document is just created. Would you mind reviewing the design [document](https://docs.google.com/document/d/1tPyqQp8Rd2yH5bhdFT676nePbfLWVfF26_l3hKVHrAo/edit#)? Thanks.

**Comment by zarda** [comment]
Updated the design doc with an additional testing item to check up the resultant image information: shape.
