### ISSUE TITLE
Concatenate stokes images

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend-ICD-test#234]
From backend issue [#611](https://github.com/CARTAvis/carta-backend/issues/611) and [PR754](https://github.com/CARTAvis/carta-backend/pull/754), to select multiple files with individual stokes and concatenate them.

ICD command:
[ConcatStokesFiles](https://carta-protobuf.readthedocs.io/en/latest/messages.html#concatstokesfiles)
[ConcatStokesFilesAck](https://carta-protobuf.readthedocs.io/en/latest/messages.html#concatstokesfilesack)

To-test:
CONCAT_STOKES_IMAGES

**Comment by acdo2002** [comment]
The designed document is [here](https://docs.google.com/document/d/1gjbuDzWQ_6TExipxp6HT0ZhlRbdm2Ba3U0JRmx_5gyc/edit)
