### ISSUE TITLE
ListProgress & StopFileList

### ISSUE THREAD

**Issue by acdo2002** [CARTAvis/carta-backend-ICD-test#240]
Should test new added ICD message: ListProgress & StopFileList

- [x] Design the test
- [x] Implementation

**Comment by acdo2002** [comment]
@kswang1029 
The [design document](https://docs.google.com/document/d/170ECmZwiwu2hI3XO_DgXHQqVmLaLhzpxZPrMZLgi6kU/edit?usp=sharing) of this test is ready, could you check it?

**Comment by kswang1029** [comment]
It looks good. Please add one test to check total number of files received in the end.
