### ISSUE TITLE
set_QA files missing?

### ISSUE THREAD

**Issue by phanicode** [CARTAvis/carta-backend-ICD-test#257]
https://www.aoc.nrao.edu/~pford/ is the link I use for set_QA and it does not contain the fits files needed for passing this test [FILEINFO_FITS_NONSTANDARD](https://github.com/CARTAvis/carta-backend-ICD-test/blob/c6600b0bd3ab4564b8821c843bd5906c519646df/src/test/FILEINFO_FITS_NONSTANDARD.test.ts#L24-L76)

The public/set_QA doesn't have it either but the frontend demo server has them

Can I have the link for the set_QA folder? . Thanks

**Comment by acdo2002** [comment]
[Here](https://drive.google.com/file/d/1Wf2aaX7wvWVH81y2OLy7Lk_80Y9FRqOE/view?usp=sharing) is the Google drive link to those files inside `FILEINFO_FITS_NONSTANDARD`.
This test is going to test whether the carta-backend can open file's header successfully.

Could you explain in more detail why you would like to do with `carta-backend-ICD-test`?
We are thinking if you are working with python CARTA backend, perhaps running each ICD message (i.e. EventType in `carta-backend-ICD-test/protobuf/shared/enums.proto`) successfully is more important than running each test.

**Comment by phanicode** [comment]
Thank you. I'm working on a python backend server and so I need to run and pass these tests 
Best,
Phani

**Comment by phanicode** [comment]
@acdo2002 I'm following a test driven approach to development as I'm new to the CARTA interface. 

Any reason that might not be a good idea?
