### ISSUE TITLE
List of ICD test image files

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-backend-ICD-test#294]
Perhaps not all images in our  270GB `set_QA` are currently used. If we can reduce it, then developers at other institutes would be able to download the images more easily and run the ICD tests on their local computer.

- Create a definitive list of the images files used by the ICD tests.

- Keep the list updated when new tests are added.

- Host the set of image files somewhere suitable for download.

**Comment by acdo2002** [comment]
Yes, I think it is good to provide a webpage let the developers can download the images (according to the definitive list) they would like to test.
For the specific test, they perhaps don't need the entire images.

**Comment by ajm-asiaa** [comment]
@I-Chenn Can take over this issue now
