### ISSUE TITLE
Problem with the spire500_ext.fits file

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-backend-ICD-test#36]
Problem with the spire500_ext.fits image in **FILETYPE_PARSER.test.ts** and **FILEINFO.test.ts**

>     Expected value to equal:
>       ["0", "1", "2", "3", "4", "5", "6", "7"]
>     Received:
>       ["1 ExtName: image   ", "6 ExtName: error   ", "7 ExtName: coverage"]

Easy fix:
In FILEINFO.test.ts, change line 328 from
` hdu: "0", HDUList: ["0", "1", "2", "3", "4", "5", "6", "7"], `
to
` hdu: "0", HDUList: ["1 ExtName: image   ", "6 ExtName: error   ", "7 ExtName: coverage"], `

Similarly, in FILETYPE_PARSER.test.ts, change line 71 from
` ["spire500_ext.fits", CARTA.FileType.FITS, 17591040, ["0", "1", "2", "3", "4", "5", "6", "7"]],`
to 
` ["spire500_ext.fits", CARTA.FileType.FITS, 17591040, ["1 ExtName: image   ", "6 ExtName: error   ", "7 ExtName: coverage"]],`

**Comment by kswang1029** [comment]
this is due to the new feature on how we display FITS files with multiple HDUs. Now we only display "images". Other types (e.g., "binary") are ignored. 
https://github.com/CARTAvis/carta-backend/pull/240

**Comment by ajm-asiaa** [comment]
Issue fixed
