### ISSUE TITLE
Inconsistent CHECK_RASTER_TILE_DATA

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-backend-ICD-test#49]
I am having some trouble getting the updated ICD tests to run in the CI environment.

Here the `CHECK_RASTER_IMAGE_DATA_noCompression.test.ts` test only runs successfully if the carta-backend is freshly started. If another test is run beforehand, or the test is repeated, then it fails every time.  

> FAIL  src/test/CHECK_RASTER_IMAGE_DATA_noCompression.test.ts (8.713s)
>   CHECK_RASTER_IMAGE_DATA_noCompression test: Testing message RASTER_IMAGE_DATA without compression
>     Go to "public/set_QA" folder
>       Open image "G14.114-0.574.continuum.image.pbcor.fits"
>         ✕ OPEN_FILE_ACK should arrive within 5000 ms. (5005ms)
>         ✓ OPEN_FILE_ACK.success = true (8ms)
>         ✓ OPEN_FILE_ACK.file_info.file_id = 0 (1ms)
>         ✓ Assert OPEN_FILE_ACK.file_info (3ms)
>         ✓ assert OPEN_FILE_ACK.file_info_extended (2ms)
>         ✓ assert OPEN_FILE_ACK.file_info_extended.computed_entries (6ms)
>         ✓ assert OPEN_FILE_ACK.file_info_extended.header_entries (23ms)
>         ✕ REGION_HISTOGRAM_DATA.file_id = 0 (1ms)
>         ✕ REGION_HISTOGRAM_DATA.stokes = 0
>         ✕ Assert REGION_HISTOGRAM_DATA.histogram

**Comment by zarda** [comment]
There is a trouble about running CURSOR_SPATIAL_PROFILE.test.ts. The current /dev branch rarely pass it on CARTA demo server.
