### ISSUE TITLE
Concurrent file read

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend-ICD-test#80]
A concurrent test for ICD command OpenFile and CloseFile:

Use case:
1) 10+ users login and access the same image file
2) 5 users login and access different image files

Usage:
Backend do not crash
Process time be less than serial mode

Design:
[Design Doc](https://docs.google.com/document/d/1h098N2xCB4Rburjm8G9XTcN3MqfMjVhwt_Qrpy-69Os/edit?pli=1)
OPEN_IMAGE_CONCURRENT

**Comment by zarda** [comment]
@robsimmonds @acdo2002 
We could have a discussion about how to make the testing here.
An easy solution is to upgrade a current test including both design table and testing code.

**Comment by kswang1029** [comment]
better use one backend for one user.
