### ISSUE TITLE
review/revise existing test doc

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#82]
https://docs.google.com/document/d/1h098N2xCB4Rburjm8G9XTcN3MqfMjVhwt_Qrpy-69Os/edit#

- [ ] ACCESS_CARTA_DEFAULT
- [ ] ACCESS_CARTA_UNKNOWN_SESSION
- [ ] GET_FILELIST_DEFAULT_PATH
- [ ] GET_FILELIST_UNKNOWN_PATH
- [ ] FILETYPE_PARSER
- [ ] FILEINFO_FITS
- [ ] FILEINFO_CASA
- [ ] FILEINFO_HDF5
- [ ] FILEINFO_MIRIAD
- [ ] FILEINFO_FITS_MULTIHDU
- [ ] FILEINFO_EXCEPTIONS
- [ ] CURSOR_SPATIAL_PROFILE
- [ ] CURSOR_SPATIAL_PROFILE_NaN
- [ ] CHECK_RASTER_TILE_DATA
- [ ] TILE_DATA_REQUEST
- [ ] TILE_DATA_ORDER_TEST
- [ ] OPEN_IMAGE_APPEND
- [ ] CURSOR_SPECTRAL_PROFILE
- [ ] CURSOR_SPECTRAL_PROFILE_NaN
- [ ] ANIMATOR_NAVIGATION
- [ ] ANIMATOR_DATA_STREAM
- [ ] ANIMATOR_NAVIGATION_EXCEPTION
- [ ] ANIMATOR_PLAYBACK
- [ ] PER_CUBE_HISTOGRAM
- [ ] PER_CUBE_HISTOGRAM_HDF5
- [ ] PER_CUBE_HISTOGRAM_CANCELLATION
- [ ] REGION_OPERATIONS
- [ ] REGION_STATISTICS_RECTANGLE
- [ ] REGION_STATISTICS_ELLIPSE
- [ ] REGION_STATISTICS_POLYGON
- [ ] REGION_SPECTRAL_PROFILE_RECTANGLE
- [ ] REGION_SPECTRAL_PROFILE_ELLIPSE
- [ ] REGION_HISTOGRAM_RECTANGLE
- [ ] REGION_SPECTRAL_PROFILE_STOKES
- [ ] REGION_DATA_STREAM
- [ ] RESUME_SESSION
- [ ] CASA_REGION_INFO
- [ ] CASA_REGION_IMPORT_INTERNAL
- [ ] CASA_REGION_IMPORT_EXPORT
- [ ] CASA_REGION_IMPORT_EXCEPTION
- [ ] CASA_REGION_EXPORT
- [ ] DS9_REGION_IO_EXTERNAL

**Comment by zarda** [comment]
Almost all entries are reviewed and revised.
