### ISSUE TITLE
preparing a set of basic performance monitoring tests

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend-ICD-test#85]
need a set of basic performance monitoring tests for CI

- [x] PERF_LOAD_IMAGE
- [x] PERF_RASTER_TILE_DATA
- [x] PERF_CONTOUR_DATA
- [x] PERF_CUBE_HISTOGRAM
- [x] PERF_REGION_SPECTRAL_PROFILE
- [x] PERF_ANIMATION_PLAYBACK

**Comment by kswang1029** [comment]
preparation of test recipes in progress.

**Comment by kswang1029** [comment]
Basic recipes done: https://docs.google.com/document/d/1VrvXs7x7wH9EAd8Nl9QSH5hDQv_omNmghV4EAs-U0Q8/edit

@acdo2002 could you review it?

**Comment by kswang1029** [comment]
While @acdo2002 is reviewing the recipes, @zarda could you start implementation?

**Comment by kswang1029** [comment]
@acdo2002 Could you work on the implementation?

**Comment by acdo2002** [comment]
Yes, let me write the summary of #81 first and then I will move on this.

**Comment by zarda** [comment]
After sending OPEN_FILE, the REGION_HISTOGRAM_DATA might not return for large image file: cube_A_19200_z00100.xxx .However the rest step can work on after this failure.

**Comment by zarda** [comment]
The PERF_RASTER_TILE_DATA can not finish the last step even if the waiting time is up to 20 seconds.

**Comment by acdo2002** [comment]
Progress report:
- PERF_LOAD_IMAGE
   - [x] implementation (@zarda )
   - [x] verify (@acdo2002 )
 PASS  src/test/PER_LOAD_IMAGE.test.ts (20.684s)
  PERF_LOAD_IMAGE
    Go to "set_QA_performance" folder
      open the file "set_QA_performance/cube_A/cube_A_02400_z00100.fits"
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 7000 ms (73ms)
        ✓ RASTER_TILE_DATA should arrive within 5000 ms (48ms)
      open the file "set_QA_performance/cube_A/cube_A_04800_z00100.fits"
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 7000 ms (244ms)
        ✓ RASTER_TILE_DATA should arrive within 5000 ms (44ms)
      open the file "set_QA_performance/cube_A/cube_A_09600_z00100.fits"
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 7000 ms (882ms)
        ✓ RASTER_TILE_DATA should arrive within 5000 ms (85ms)
      open the file "set_QA_performance/cube_A/cube_A_19200_z00100.fits"
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 7000 ms (3393ms)
        ✓ RASTER_TILE_DATA should arrive within 5000 ms (210ms)
      open the file "set_QA_performance/cube_A/cube_A_02400_z00100.image"
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 7000 ms (108ms)
        ✓ RASTER_TILE_DATA should arrive within 5000 ms (49ms)
      open the file "set_QA_performance/cube_A/cube_A_04800_z00100.image"
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 7000 ms (341ms)
        ✓ RASTER_TILE_DATA should arrive within 5000 ms (62ms)
      open the file "set_QA_performance/cube_A/cube_A_09600_z00100.image"
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 7000 ms (1180ms)
        ✓ RASTER_TILE_DATA should arrive within 5000 ms (99ms)
      open the file "set_QA_performance/cube_A/cube_A_19200_z00100.image"
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 7000 ms (2350ms)
        ✓ RASTER_TILE_DATA should arrive within 5000 ms (210ms)
      open the file "set_QA_performance/cube_A/cube_A_02400_z00100.hdf5"
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 7000 ms (160ms)
        ✓ RASTER_TILE_DATA should arrive within 5000 ms (52ms)
      open the file "set_QA_performance/cube_A/cube_A_04800_z00100.hdf5"
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 7000 ms (492ms)
        ✓ RASTER_TILE_DATA should arrive within 5000 ms (85ms)
      open the file "set_QA_performance/cube_A/cube_A_09600_z00100.hdf5"
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 7000 ms (1453ms)
        ✓ RASTER_TILE_DATA should arrive within 5000 ms (87ms)
      open the file "set_QA_performance/cube_A/cube_A_19200_z00100.hdf5"
        ✓ OPEN_FILE_ACK and REGION_HISTOGRAM_DATA should arrive within 7000 ms (5141ms)
        ✓ RASTER_TILE_DATA should arrive within 5000 ms (208ms)

Test Suites: 1 passed, 1 total
Tests:       24 passed, 24 total
Snapshots:   0 total
Time:        21.484s

- PERF_RASTER_TILE_DATA
   - [x] implementation (@zarda )
   - [ ] verify is on working
- PERF_CONTOUR_DATA
- PERF_CUBE_HISTOGRAM
- PERF_REGION_SPECTRAL_PROFILE
- PERF_ANIMATION_PLAYBACK

**Comment by zarda** [comment]
In case of single testing for one file in PERF_REGION_SPECTRAL_PROFILE, the running time can be less than 20 seconds. But the running time for large file may exceed 20 seconds if we run all files at once.

**Comment by zarda** [comment]
No issue for this test anymore.
