### ISSUE TITLE
ws/wss issue

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-backend-ICD-test#87]
This is just a reminder that we may need to investigate, and hopefully solve, the websocket (ws) and secure websocket (wss) issue at some stage. The issue is that most of the complex ICD tests no longer work if we are using 'ws' in /src/test/config.json e.g. ws://127.0.0.1:3002. 
However, the tests work fine if using 'wss' from another server. e.g. wss://carta.asiaa.sinica.edu.tw/socketdev

An example of such a test that works with 'wss' but not with 'ws' is src/test/ANIMATOR_DATA_STREAM.test.ts

**Comment by zarda** [comment]
I tested several version of node.js including 8.x, 10.x, 12.x and confirmed that the node.js is independent of this issue.

**Comment by veggiesaurus** [comment]
I wonder if this is actually related to a timing issue. Local connections to a websocket server will likely be much faster than connecting to a remote server over WSS. @ajm-asiaa could you check this?

**Comment by ajm-asiaa** [comment]
@veggiesaurus OK I just checked. Your assumption appears to be correct, but it doesn't seem to be _that_ much different. 

I just ran the `ACCESS_CARTA_DEFAULT` ICD test and recorded the actual result from the "should get "REGISTER_VIEWER_ACK" within 500 ms" part of the test. In each case I ran the test 10 times and got the average value.

1. ws:// with port number on same server e.g. 
`"serverURL": "ws://localhost:3002",`
Average **81.7ms**

2. ws:// with a port number to different server: e.g.
`"serverURL": "ws://carta.sinica.edu:4000",`
Average **96.2ms.**

3. wss:// with reverse proxy to different server: e.g.
`"serverURL": "wss://carta.sinica.edu/sockettest",`
Average **100.3 ms**

It seems the network between servers, plus going through the Nginx webserver slows things down. 

But if local WS connections are faster than remote WSS connections, then why do most tests using WS fail and only WSS succeed? 
Do you think WS is failing because it is somehow too fast?

**Comment by zarda** [comment]
Theoretically, the messages on websocket are queued in order, the incoming command should wait for the previous one. The testing script have to detect any returning message until sending the next command. 
There three schemes: 1) speed up the backend, 2) slow down the testing commands, or 3) skip the decoding process in Jest. About the second propose, we offered a longer timeout or waiting time between two frames in the test: Animator. About the third one, @acdo2002 tested with a new Jest code, which passed the decoding process.

**Comment by zarda** [comment]
We just update the websocket lib for the environment from jsdom to node.js. @ajm-asiaa Would you mind giving it a try about this issue? Thanks.

**Comment by ajm-asiaa** [comment]
@zarda You fixed it! All ICD tests against the carta-backend running on the same server with ws:// seems to be working fine now! That is fantastic! Great job!

**Comment by zarda** [comment]
I can't explain why the websocket in node.js is more compatiable than that in jsdom since the frontend is run on a web browser.

**Comment by acdo2002** [comment]
Thanks! then I will change from wss to ws for the long-term performance tests!!!
