### ISSUE TITLE
REGISTER_VIEWER_ACK.server_feature_flags

### ISSUE THREAD

**Issue by ajm-asiaa** [CARTAvis/carta-backend-ICD-test#91]
In the `ACCESS_CARTA_DEFAULT.test.ts` test, the following part is failing for me: 

> ✕ REGISTER_VIEWER_ACK.server_feature_flags = 0 (3ms)

I'm wondering should it still be working, or has it become obsolete?

**Comment by kswang1029** [comment]
server_feature_flags should still work I think. @acdo2002 could you have a look?

**Comment by acdo2002** [comment]
For this specific problem in `ACCESS_CARTA_DEFAULT.test.ts`:
Here I wrote the report for local backend (built on my Mac): 
It looks there is a change in manual. If I want to pass this test, I should change  

> RegisterViewerAckTemp.serverFeatureFlags = 8

I need to check with server backend later, and there are several change(?) in the past two days. Some updates for test codes are required. I also would like to discuss with others why this happened.

**Comment by ajm-asiaa** [comment]
Issue resolved. Thanks @acdo2002
